In [1]:
import os
import pandas as pd

week_month_folder = 'etf_week_month_data'

fe_week_df = pd.read_csv(os.path.join(week_month_folder, 'fe_week_data.csv'))
fe_week_df.head()

,FNCL,BDCL,IYG,BDCZ,IAI,PFI,KBWP,KBE,RWW,KCE,...,IAK,FAZ,DPST,KBWB,FINU,SEF,IYF,XLF,BDCS,WDRW
0,-0.075228,-0.028976,-0.097183,-0.017060,-0.101034,-0.064516,-0.058590,-0.095562,-0.089488,-0.127489,...,-0.076842,0.186166,-0.323114,-0.102023,-0.230757,0.068985,-0.074268,-0.078281,-0.026835,0.000000
1,-0.032562,-0.251410,-0.037970,-0.059543,-0.056302,-0.024885,-0.015660,-0.045024,-0.029144,-0.058292,...,-0.016043,0.080334,-0.158032,-0.043119,-0.183237,0.033600,-0.031340,-0.031746,-0.101506,0.859497
2,-0.003939,0.051948,-0.012300,0.000000,-0.003655,-0.003926,0.003122,-0.026764,-0.007044,0.007605,...,0.002773,0.003441,-0.059752,-0.021556,0.004155,0.000533,-0.003270,-0.006579,0.020219,-3.543025
3,0.020070,0.020210,0.022909,-0.029895,0.018217,0.012685,0.026276,0.026725,0.015260,-0.003817,...,0.019452,-0.069754,0.059590,0.024383,0.029118,-0.020120,0.020330,0.020258,0.009204,0.770207
4,-0.033919,-0.026114,-0.042956,0.000328,-0.045297,-0.041468,-0.017230,-0.033928,-0.032959,-0.046206,...,-0.033730,0.088324,-0.021107,-0.038291,-0.105273,0.033123,-0.036394,-0.036754,-0.006539,0.068346

In [2]:
fe_month_df = pd.read_csv(os.path.join(week_month_folder, 'fe_month_data.csv'))
fe_month_df.head()

,FNCL,BDCL,IYG,BDCZ,IAI,PFI,KBWP,KBE,RWW,KCE,...,IAK,FAZ,DPST,KBWB,FINU,SEF,IYF,XLF,BDCS,WDRW
0,-0.092242,-0.196108,-0.126440,-0.109834,-0.146012,-0.081395,-0.043648,-0.144114,-0.111908,-0.188659,...,-0.069860,0.202093,-0.527002,-0.145687,-0.407999,0.082654,-0.088960,-0.097146,-0.097997,0.853321
1,-0.025326,0.042294,-0.043910,0.000328,-0.024604,-0.000352,0.003678,-0.043785,-0.006048,-0.018606,...,-0.020056,0.035327,0.021412,-0.056003,-0.065010,0.016578,-0.026173,-0.029872,0.022751,-4.062709
2,0.063033,0.136223,0.056939,0.096439,0.055303,0.062149,0.059231,0.067501,0.051831,0.075244,...,0.060722,-0.259416,0.155769,0.060194,0.172515,-0.079054,0.065130,0.062667,0.073529,-0.302072
3,0.027758,-0.003729,0.049215,0.004431,0.006371,-0.027165,-0.032143,0.064099,0.032437,0.022345,...,0.009134,-0.099663,0.157458,0.071348,0.062464,-0.028487,0.026355,0.034749,0.002933,-0.175894
4,0.025299,-0.013224,0.023905,-0.004948,0.045846,0.033793,0.038966,0.029605,0.017198,0.034892,...,0.040579,-0.081467,0.046826,0.027322,0.067189,-0.026188,0.022170,0.018526,-0.008876,-0.133788

In [3]:
cse_week_df = pd.read_csv(os.path.join(week_month_folder, 'cse_week_data.csv'))
cse_week_df.head()

,XLP,PBJ,FSTA,EMCG,WBIL,RHS,KXI,PSL,PSCC,UGE,IYK,VDC,WBIE,WBID,SZK,ECON,FXG
0,-0.029988,-0.039380,-0.033095,-0.078090,-0.042096,-0.031381,-0.043405,-0.037260,-0.043528,-0.102288,-0.052208,-0.032643,-0.057483,-0.051852,0.103376,-0.088582,-0.028935
1,-0.014907,-0.023794,-0.016297,-0.057075,-0.005126,-0.019208,-0.015490,-0.026049,-0.008627,-0.064154,-0.021308,-0.016427,-0.009704,-0.010479,0.051779,-0.040490,-0.027837
2,0.020085,0.013368,0.018714,-0.011873,0.003344,0.017099,0.023033,0.011486,0.009871,0.042682,0.021149,0.017733,0.006930,0.006051,-0.041581,0.026957,0.005678
3,0.028960,0.028508,0.030353,0.068833,0.008199,0.027876,0.037382,0.029835,0.014037,0.037989,0.030292,0.030061,0.009050,0.012248,-0.065351,0.060857,0.027158
4,-0.022768,-0.047445,-0.022605,-0.032110,-0.017338,-0.020316,-0.020774,-0.045668,-0.034262,-0.042596,-0.032340,-0.022418,-0.022078,-0.022389,0.054726,-0.022908,-0.019235

In [4]:
cse_month_df = pd.read_csv(os.path.join(week_month_folder, 'cse_month_data.csv'))
cse_month_df.head()

,XLP,PBJ,FSTA,EMCG,WBIL,RHS,KXI,PSL,PSCC,UGE,IYK,VDC,WBIE,WBID,SZK,ECON,FXG
0,0.005319,-0.019956,0.000990,-0.073778,-0.035375,-0.004415,0.003535,-0.020669,-0.027513,-0.080279,-0.020038,0.000000,-0.050750,-0.043504,0.056579,-0.035054,-0.023015
1,0.003142,0.001581,0.004271,0.004094,-0.015672,0.019023,-0.013351,0.000539,0.037817,0.035552,0.006449,0.004013,-0.018527,-0.018309,-0.051660,-0.033199,0.022937
2,0.040332,0.026178,0.038838,0.122621,0.016789,0.032854,0.053815,0.023162,0.070161,0.098388,0.049316,0.042344,0.021305,0.021718,-0.094950,0.120354,0.035776
3,-0.014532,-0.005886,-0.012468,0.004831,-0.013473,-0.009285,-0.004229,-0.016771,0.029101,-0.010800,-0.005091,-0.010831,-0.013694,-0.020927,0.007021,0.008772,0.007104
4,0.006836,0.000310,0.009186,-0.029492,0.011247,0.010256,0.004722,0.010242,0.017098,0.003140,0.004888,0.008370,0.002658,0.015694,-0.014758,-0.026565,0.009806

## Sharpe Omega measure

In [5]:
# Risk-free rate
week_riskfree = (2.45785 / 100 ) / 52
month_riskfree = (2.45785 / 100 ) / 12

fe_name = fe_week_df.columns
cse_name = cse_week_df.columns

In [6]:
def Ep_val_uni(data, rf):
    fil = (rf > data[name])
    return (data[name][fil] - rf).mean()

def Ep_val(data):
    return (data[name].mean())


# Expected values for Financials Equity
fe_expect_val = pd.DataFrame()
for name in fe_name:
    fe_expect_val[name] = [Ep_val(fe_week_df), Ep_val(fe_month_df), Ep_val_uni(fe_week_df, week_riskfree), Ep_val_uni(fe_week_df, month_riskfree)]

fe_EpX = fe_expect_val.T
fe_EpX.columns = ['Expect_X_all_week','Expect_X_all_month','Expect_X_part_week','Expect_X_part_month']
fe_EpX.head()

,Expect_X_all_week,Expect_X_all_month,Expect_X_part_week,Expect_X_part_month
FNCL,0.001593,0.007284,-0.019372,-0.020417
BDCL,-0.001499,-0.006152,-0.032178,-0.032920
IYG,0.001825,0.007893,-0.021861,-0.021443
BDCZ,-0.000331,-0.001344,-0.007004,-0.008518
IAI,0.001872,0.009026,-0.021369,-0.022944

In [7]:
cse_expect_val = pd.DataFrame()
for name in cse_name:
    cse_expect_val[name] = [Ep_val(cse_week_df), Ep_val(cse_month_df), Ep_val_uni(cse_week_df, week_riskfree), Ep_val_uni(cse_week_df, month_riskfree)]

# Expected values for Consumer Staples Equity
cse_EpX = cse_expect_val.T
cse_EpX.columns = ['Expect_X_all_week','Expect_X_all_month','Expect_X_part_week','Expect_X_part_month']
cse_EpX.head()

,Expect_X_all_week,Expect_X_all_month,Expect_X_part_week,Expect_X_part_month
XLP,0.000330,0.001388,-0.013469,-0.013445
PBJ,-0.000152,-0.000099,-0.014401,-0.014955
FSTA,0.000381,0.001594,-0.014125,-0.013352
EMCG,0.000534,0.002036,-0.019204,-0.019617
WBIL,0.000769,0.003511,-0.011546,-0.011412

In [8]:
# FE Ranking
fe_rank_weekly = pd.DataFrame() 
fe_rank_monthly = pd.DataFrame()

fe_sharpOmeasure_weekly = pd.DataFrame()
fe_sharpOmeasure_monthly = pd.DataFrame()
fe_sharpOmeasure_weekly["Weekly Sharpe Omega"] = (fe_EpX["Expect_X_all_week"] - week_riskfree) / fe_EpX["Expect_X_part_week"]
fe_sharpOmeasure_monthly["Monthly Sharpe Omega"] = (fe_EpX['Expect_X_all_month'] - month_riskfree) / fe_EpX["Expect_X_part_month"]

fe_rank_weekly["Financials_Equity_Sharpe_Omega_week_rank"] = fe_sharpOmeasure_weekly.sort_values(by = "Weekly Sharpe Omega", ascending= False).index
fe_rank_monthly["Financials_Equity_Sharpe_Omega_month_rank"] = fe_sharpOmeasure_monthly.sort_values(by = "Monthly Sharpe Omega", ascending= False).index

### Result of Financials Equity

In [9]:
fe_sharp_concat_df = pd.concat([fe_rank_weekly, fe_rank_monthly], axis=1)
fe_sharp_concat_df.head(15)

,Financials_Equity_Sharpe_Omega_week_rank,Financials_Equity_Sharpe_Omega_month_rank
0,WDRW,FAZ
1,FAZ,FINZ
2,FINZ,SKF
3,SKF,SEF
4,SEF,BDCZ
5,BDCZ,DXJF
6,DXJF,WDRW
7,LBDC,PEX
8,PEX,LBDC
9,BDCL,EUFN
10,EUFN,BDCL
11,BDCS,BDCS
12,DPST,LMLP
13,LMLP,BIZD
14,BIZD,DPST

### Result of Consumer Staples Equity

In [10]:
# CSE Ranking
cse_rank_weekly = pd.DataFrame() 
cse_rank_monthly = pd.DataFrame()

cse_sharpOmeasure_weekly = pd.DataFrame()
cse_sharpOmeasure_monthly = pd.DataFrame()
cse_sharpOmeasure_weekly["Weekly Sharpe Omega"] = (cse_EpX["Expect_X_all_week"] - week_riskfree) / cse_EpX["Expect_X_part_week"]
cse_sharpOmeasure_monthly["Monthly Sharpe Omega"] = (cse_EpX['Expect_X_all_month'] - month_riskfree) / cse_EpX["Expect_X_part_month"]

cse_rank_weekly["Consumer_Staples_Equity_Sharpe_Omega_week_rank"] = cse_sharpOmeasure_weekly.sort_values(by = "Weekly Sharpe Omega", ascending= False).index
cse_rank_monthly["Consumer_Staples_Equity_Sharpe_Omega_month_rank"] = cse_sharpOmeasure_monthly.sort_values(by = "Monthly Sharpe Omega", ascending= False).index

In [12]:
cse_sharp_concat_df = pd.concat([cse_rank_weekly, cse_rank_monthly], axis=1)
cse_sharp_concat_df.head(15)

,Consumer_Staples_Equity_Sharpe_Omega_week_rank,Consumer_Staples_Equity_Sharpe_Omega_month_rank
0,SZK,SZK
1,WBID,FXG
2,FXG,WBID
3,PBJ,PBJ
4,ECON,ECON
5,XLP,KXI
6,IYK,XLP
7,FSTA,IYK
8,KXI,FSTA
9,RHS,RHS
10,VDC,VDC
11,UGE,UGE
12,EMCG,EMCG
13,WBIE,WBIE
14,WBIL,WBIL

In [13]:
rank_folder = 'rank'
if not os.path.exists(rank_folder):
    os.mkdir(rank_folder)

fe_sharp_concat_df.to_csv(os.path.join(rank_folder, 'fe_rank.csv'), index=False)
cse_sharp_concat_df.to_csv(os.path.join(rank_folder, 'cse_rank.csv'), index=False)